// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beoutzkrtzzdopociraq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlb3V0emtydHp6ZG9wb2NpcmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3ODg3MzAsImV4cCI6MjA2NjM2NDczMH0.OicbwtkMtpOak8TdJ6B-uAbb4mTRG9_GgHOdpamf7-A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);